version: "3"
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: sag-back-end:task5
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: sag-front-end:task5
    depends_on:
      - back-end
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: sag-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
